CREATE TABLE IF NOT EXISTS `address` (
  `id` int AUTO_INCREMENT  PRIMARY KEY,
  `street` varchar(200) NOT NULL,
  `number` int NOT NULL,
  `city` varchar(100) NOT NULL,
  `country` varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS `USER_PROFILE` (
  ID bigint AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NULL,
  EMAIL VARCHAR(100) NULL,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE tinyint NOT NULL,
  ADDRESS_ID BIGINT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT timestamp(6) DEFAULT NULL,
  FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
);






